all: Versuchsaufbau/Versuchsaufbau.pdf Versuchsaufbau/clean

Versuchsaufbau/Versuchsaufbau.pdf:
	pwd
	@echo Texen
	lualatex versuchsaufbau.tex

Versuchsaufbau/clean:
	rm -rf *.log *idx *.idl *.xml *.toc *.aux *.bcf *.ind *.bbl *.blg *.ilg